/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_sample_villacortagwapo;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        this.setSize(new Dimension(471, 361));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userTxtField = new javax.swing.JTextField();
        pwdTxtField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        registerBttn = new javax.swing.JButton();
        loginBttn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(330, 220, 71, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 80, 58, 20);
        jPanel2.add(userTxtField);
        userTxtField.setBounds(110, 40, 150, 22);
        jPanel2.add(pwdTxtField);
        pwdTxtField.setBounds(110, 80, 150, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 40, 62, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 90, 280, 150);

        registerBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBttn.setText("Register");
        registerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBttnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBttn);
        registerBttn.setBounds(140, 260, 90, 23);

        loginBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBttn.setText("Login");
        loginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBttnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBttn);
        loginBttn.setBounds(250, 260, 90, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registration Form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 60, 170, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBttnActionPerformed
        // TODO add your handling code here:
         String username = userTxtField.getText();
         String password = pwdTxtField.getText();
         
         
         
         
         
         
         
         
         String sqlSelectionQuery = "SELECT * FROM tblaccounts WHERE username='"+username+"' ";
         String sqlInsertQuery = "INSERT INTO tblaccounts (username, password, category) "
                    + "VALUES ('"+username+"', '"+password+"', 'user')";
            try{
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login_sample_villacorta", "root", "");
                 Statement stmt = con.createStatement();
                 ResultSet rs = stmt.executeQuery(sqlSelectionQuery);
                 if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "User already exist");
                    userTxtField.setText("");
                    pwdTxtField.setText("");
                 } else  {
                    int rows = stmt.executeUpdate(sqlInsertQuery);
                    System.out.println("Number of rows inserted: " + rows);
                    JOptionPane.showMessageDialog(null, "You have successfully registered your account, you may now go to the login form");
                    userTxtField.setText("");
                    pwdTxtField.setText("");

                   stmt.close();
                   con.close();
                 }
            } catch(SQLException e) {
                System.out.println("Exception!");
                e.printStackTrace();
            } 
    }//GEN-LAST:event_registerBttnActionPerformed

    private void loginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBttnActionPerformed
        // TODO add your handling code here:
        UI loginForm = new UI();
        loginForm.setVisible(true);
        
    }//GEN-LAST:event_loginBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginBttn;
    private javax.swing.JPasswordField pwdTxtField;
    private javax.swing.JButton registerBttn;
    private javax.swing.JTextField userTxtField;
    // End of variables declaration//GEN-END:variables
}
