/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_sample_villacortagwapo;

import java.awt.Dimension;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        this.setSize(new Dimension(471, 361));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userTxtField = new javax.swing.JTextField();
        pwdTxtField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        loginBttn = new javax.swing.JButton();
        registerBttn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 60, 80, 20);
        jPanel3.add(userTxtField);
        userTxtField.setBounds(90, 20, 196, 22);
        jPanel3.add(pwdTxtField);
        pwdTxtField.setBounds(90, 60, 200, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 20, 80, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(80, 100, 310, 120);

        loginBttn.setBackground(new java.awt.Color(204, 204, 204));
        loginBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBttn.setText("Login");
        loginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBttnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBttn);
        loginBttn.setBounds(140, 240, 80, 30);

        registerBttn.setBackground(new java.awt.Color(204, 204, 204));
        registerBttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBttn.setText("Register");
        registerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBttnActionPerformed(evt);
            }
        });
        jPanel2.add(registerBttn);
        registerBttn.setBounds(240, 240, 80, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Form");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 60, 100, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 460, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBttnActionPerformed
        // TODO add your handling code here:
        if (counter != 5) {
             if (userTxtField.getText().equals("") || pwdTxtField.getText().equals("null")) {
                JOptionPane.showMessageDialog(null,"Missing Username or Password!");
                counter++;
                System.out.println(counter);
            } else {
                String username = userTxtField.getText();
                String pwd = pwdTxtField.getText();
                String query = "SELECT * FROM tblaccounts WHERE username = '"+username+"' && password = '"+pwd+"' ";
            try{
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login_sample_villacorta", "root", "");
                 Statement stmt = con.createStatement();
                 ResultSet rs = stmt.executeQuery(query);
                 if (rs.next()) {
               
                    if(rs.getString("category").equals("admin")) {
                        JOptionPane.showMessageDialog(null,"You are an admin");
                        userTxtField.setText("");
                        pwdTxtField.setText("");
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "You are a regular user");
                        userTxtField.setText("");
                        pwdTxtField.setText("");
                    }
               
               
                }  else {
                     counter++;
                     System.out.println(counter);
                     JOptionPane.showMessageDialog(null,"User does not exist");
                     userTxtField.setText("");
                     pwdTxtField.setText("");
                 }
            
                stmt.close();
                con.close();
            } catch(SQLException e) {
                System.out.println("Exception!");
                e.printStackTrace();
            } 
           }
           
        } else {
            userTxtField.setText("");
            pwdTxtField.setText("");
            userTxtField.setEditable(false);
            pwdTxtField.setEditable(false);
            JOptionPane.showMessageDialog(null, "You are not allowed to log in due to excessive login attempts");
        }
       
        
            
       
    }//GEN-LAST:event_loginBttnActionPerformed

    private void registerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBttnActionPerformed
        // TODO add your handling code here:
        RegistrationForm registration = new RegistrationForm();
        registration.setVisible(true);
    }//GEN-LAST:event_registerBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    
    public int counter = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loginBttn;
    private javax.swing.JPasswordField pwdTxtField;
    private javax.swing.JButton registerBttn;
    private javax.swing.JTextField userTxtField;
    // End of variables declaration//GEN-END:variables
}
